### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'output/logP.pdf'

### ISSUE THREAD

**Issue by xiaowu759** [shane5ul/pyReSpect-time#1] opened 2019-09-10 11:11 UTC
I have unpacked the package and run it according to the following command
python3 contSpec.py 
Consequently, it fails with the output of the screen

(*) Start
(*) Loading Data File: tests/test4.dat...
(*) Initial Set up...	(0.3 seconds)
(*) Building the L-curve ...Traceback (most recent call last):
  File "contSpec.py", line 614, in <module>
    H, lamC = getContSpec(par)
  File "contSpec.py", line 416, in getContSpec
    lamC, lam, rho, eta, logP, Hlam = lcurve(Gexp, Hgs, kernMat, par)
  File "contSpec.py", line 226, in lcurve
    plt.savefig('output/logP.pdf')
  File "/usr/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/matplotlib/figure.py", line 1573, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/matplotlib/backend_bases.py", line 2252, in print_figure
    **kwargs)
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_pdf.py", line 2519, in print_pdf
    file = PdfFile(filename)
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_pdf.py", line 422, in __init__
    fh = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'output/logP.pdf'

How to deal with it? I look forward to your reply.

**Comment by shane5ul** [comment] 2019-09-10 13:39
At first glance, this seems like a PDF writer issue with your installation
(savefig seems to fail).

Can you run something like this?

import numpy as np
import matplotlib.pyplot as plt

x = np.ones(10)
plt.plot(x,x)
plt.savefig('test.pdf')

**Comment by xiaowu759** [comment] 2019-09-11 05:06
I can run this successfully. But how to deal with my issue? I find that no "output" directory is created yet.

**Comment by xiaowu759** [comment] 2019-09-11 07:28
I have made another try. While the "output" directory is created manually, the python3 program can be run successfully. Therefore, I think the following commands in the code do not work as expected

if not os.path.exists("output"):
         os.makedirs("output")

How to deal with it? Thank you very much for any reply!

**Comment by shane5ul** [comment] 2019-09-11 11:54
Thank you for pointing this out to me. This feedback is useful to me to
improve the code.

Can you please tell me (i) what operating system are you running this
program on (Mac/Windows/Linux)? (ii) what version of the OS are you using?

Best, Sachin

**Comment by xiaowu759** [comment] 2019-09-11 12:06
I mean OpenSuse15.1. Thanks a lot.

**Comment by shane5ul** [comment] 2019-09-11 12:38
I am unable to reproduce that error on my Ubuntu machine and Mac. But could
you tell me what happens if you simply run the following python code

import os
print(os.path.exists("test"))
if not os.path.exists("test"):
    os.makedirs("test")
    print(os.path.exists("test"))

And try the following as well, replacing double quotes with single quotes.

import os
print(os.path.exists('test'))
if not os.path.exists('test'):
    os.makedirs('test')
    print(os.path.exists('test'))

Thanks, Sachin

**Comment by xiaowu759** [comment] 2019-09-11 13:11
I have tried it according to your suggestions. For the case of either double quotes or single quotes, the same results can be obtained. Specially, for both of them, the output of the screen is 
False
True
, and a  directory named "test" is created as expected.
Thank you very much for all efforts spent on the valuable code and my issue.

**Comment by xiaowu759** [comment] 2019-09-11 13:50
However, if I changed the original code 

if not os.path.exists("output"):
 os.makedirs("output")

as 

import os
print(os.path.exists("output"))
if not os.path.exists("output"):
    os.makedirs("output")
    print(os.path.exists("output"))

The same errors can be yielded as before.

**Comment by shane5ul** [comment] 2019-09-11 17:37
Thanks, I now fixed it in the code on GitHub.

**Comment by xiaowu759** [comment] 2019-09-11 22:50
It really works. Thank you very much!

**Closed** 2019-09-11 22:50 UTC
